Change `sys.maxint` to `sys.maxsize` for Python 3
`sys` in Python 3 does no longer provide a `maxint` attribute; Python 2 supports both `sys.maxint` and `sys.maxsize`. (See [Python 2 docs](https://docs.python.org/2.7/library/sys.html#sys.maxint) and [Python 3](https://docs.python.org/3/library/sys.html#sys.maxsize) docs.)

Without this change the code fail with error:

```
AttributeError: module 'sys' has no attribute 'maxint'
```

With the change the code works (tested in Glyphs 3 on macOS Big Sur, Python 3.8.2).